apiVersion: v1
kind: Service
metadata:
  name: service-products
  namespace: ninja
spec:
  type: NodePort
  selector:
    app: products
  ports:
  - name: service-products
    port: 3001
    targetPort: port-products