apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: ninja
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: service-frontend
    port: 3000
    targetPort: 31000