apiVersion: v1
kind: Service
metadata:
  name: service-shopping
  namespace: ninja
spec:
  type: NodePort
  selector:
    app: shopping
  ports:
  - name: service-shopping
    port: 3002
    targetPort: port-shopping